[package]
name = "galera-cli"
version = "0.1.0"
authors = ["Ondřej Pešek <iTzBoboCz@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
galera = { path = "../" }
clap = "=3.0.9"
